"""add new records

Revision ID: 23879149ce55
Revises: 1b20b7a1e783
Create Date: 2021-08-26 18:01:08.334307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23879149ce55'
down_revision = '1b20b7a1e783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
